INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 1.0, '', 'Have not received or gotten update since mid December.', 'Jodie', '', true, true, 0, TIMESTAMP '2024-01-11T18:32:10Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'Size looked bigger when I received them then the picture so I like. We''ll see how long they last. They haven''t chewed on them constantly so not sure how long they will last yet', 'Ashley', '', true, true, 0, TIMESTAMP '2024-01-10T03:47:05Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 2.0, '', 'Small was too small for an aggressive chewer and quickly destroyed.', 'David', '', true, true, 0, TIMESTAMP '2023-12-20T20:54:46Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 2.0, '', 'Love the idea - sadly, the size we got was too small for our aggressive chewer and was quickly shredded. That large and extra large were better but don''t fit in her mouth.', 'David', '', true, true, 0, TIMESTAMP '2023-12-20T20:53:55Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'My dog loves hers! Chews on it all the time!', 'Jeff', '', true, true, 0, TIMESTAMP '2023-12-18T13:39:12Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 4.0, '', 'I have 2 Pitties, the younger one loves to chew on sticks and she absolute loves her Mumbie, the older one isn’t much of a chewer but he too likes chewing on the Mumbie, which was surprising, because he’s never been much of a chewer. They do tend to make a mess indoors, so I limit their chewing time indoors right now that it’s too cold to keep them outdoor.', 'Yolanda', '', true, true, 0, TIMESTAMP '2023-12-17T19:51:22Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'My dogs LOVE THESE!!', 'Amalia', '', true, true, 0, TIMESTAMP '2023-12-12T22:48:06Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'Awesome', 'Eric', '', true, true, 0, TIMESTAMP '2023-12-12T21:16:41Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'My dog loves it, that’s all that matters!', 'Lynette', '', true, true, 0, TIMESTAMP '2023-12-12T20:34:08Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 4.0, '', 'My dogs love these! They keep them very occupied.', 'Connie', '', true, true, 0, TIMESTAMP '2023-12-08T19:17:44Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 1.0, '', 'My dogs wouldn’t even touch them.', 'rhonda', '', true, true, 0, TIMESTAMP '2023-12-07T19:10:19Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 2.0, '', 'Not too impressed with it.. won’t buy it again', 'Paul', '', true, true, 0, TIMESTAMP '2023-12-06T02:39:12Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 3.0, '', 'This is probably a good product for dogs who don’t chew as hard as my mini Aussie does she had it maybe 5 to 10 minutes at the most and already whittled the end down to look like a pencil LOL
I think it’s probably a fine product. Just not good for really hard chewers.', 'Barbara', '', true, true, 0, TIMESTAMP '2023-12-05T17:23:48Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'My puppy loves them', 'Mary', '', true, true, 0, TIMESTAMP '2023-11-30T19:03:03Z', '[]'::jsonb);
