INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'This product is perfect for a teething Labrador', 'Anna', '', true, true, 0, TIMESTAMP '2025-10-28T19:32:33Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Puppies love chewing', 'Our two puppies love to chew on this chew! Keeps them busy and out of trouble.', 'Mary M.', '', true, true, 0, TIMESTAMP '2025-10-23T21:38:59.044662Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Nice product ', 'Great natural choice! ', 'Betty O.', '', true, true, 0, TIMESTAMP '2025-10-12T03:04:34.081385Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/53c7378c-98e4-431d-9a42-1777e5824dec.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'As described! Great quality smoothe wood. My dog liked it immediately.', 'Sharon', '', true, true, 0, TIMESTAMP '2025-10-11T23:07:27Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Coffee wood', 'If your dog likes to chew sticks , this is the best option', 'Susan M.', '', true, true, 0, TIMESTAMP '2025-10-09T15:19:28.420279Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Lil boi loves his chew!', 'I got the small for my Havanese. He loves it! Goes between this and the coconut ring. He can’t decide which is his favorite!', 'Kim K.', '', true, true, 0, TIMESTAMP '2025-10-08T13:52:23.031482Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Heavy chewer approved!', 'Ace loves his!  And I love that it''s all natural so I dont have to worry about him enjoying it!', 'Travis C.', '', true, true, 0, TIMESTAMP '2025-10-04T23:37:45.888378Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 3.0, '', 'Too messy for me', 'JACQUELINE', '', true, true, 0, TIMESTAMP '2025-09-27T19:13:17Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 3.0, '', 'Pups love them! Really satisfies their urge to gnaw and chew BUT woodchips get stuck in fabric and its hard to get out… a shirpa blanket is covered in woodchips now 

I wont buy again for that reason. 
Ostrich bones are the best IMO', 'JACQUELINE', '', true, true, 0, TIMESTAMP '2025-09-22T04:03:03Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'My dog LOVES it!', 'These things are fantastic! I have a big dog who loves sticks and plastic chew toys. Got him an extra large and he absolutely LOVES it! Started chewing the minute he got it and hasn’t stopped! THANK YOU Mumbies!', 'Lori K.', '', true, true, 0, TIMESTAMP '2025-09-22T01:41:48.792047Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/da7fceaf-3c5c-4cb3-9434-5282887254ce.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'MY DOGS LOVE ''EM!', 'My dogs love their mumbie chew sticks. This is a great company and they arrived quickly.  I will definitely order more! ', 'Janice V.', '', true, true, 0, TIMESTAMP '2025-09-17T01:10:19.454837Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/33c30989-9557-4565-9564-d8d980948caa.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/3aa2c3ee-46d5-483a-b174-f25bc1b8636d.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'These are great', 'These are great for my super chewers.It''s nice that they are natural.And will keep my dog from eating the stuff in the yard.I am very happy with my purchase.I would recommend buying these', 'Penny M.', '', true, true, 0, TIMESTAMP '2025-09-16T19:33:35.833770Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/8be7ac65-dacb-42c6-ba21-843393972ff6.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 4.0, '', 'My beagle loves this chew. Although I worry about splinters or shards coming off. But so far not yet.', 'Kimberly', '', true, true, 0, TIMESTAMP '2025-09-12T14:11:51Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Love them keeps them occupied', 'My dog loves them', 'Marcie N.', '', true, true, 0, TIMESTAMP '2025-09-04T05:35:19.162581Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Satisfied', 'My dog loves her mumbies. ', 'Quin N.', '', true, true, 0, TIMESTAMP '2025-09-03T21:46:29.533026Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Good Chew For Dogs Who Like Sticks', 'Ordering process was easy and the order arrived quickly. My dog understood it was a chew toy right away and enjoyed it. I rotate it with other chews like benebones, yak chews, bully sticks, sweet potatos. Make sure you watch your dog as they work towards the middle. The chew seems to splinter more in the middle', 'Andrew C.', '', true, true, 0, TIMESTAMP '2025-09-01T21:07:34.417382Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'My second time buying Mumbies for my dogs. They will chose these over anything edible to chew on. They never splinter and theyre so smooth! Will buy again.', 'Sheri', '', true, true, 0, TIMESTAMP '2025-08-21T21:40:02Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great dog chew!', 'Excellent wood chew for my medium/large dog!  He is quite the chewer and destroys most toys.  These chews are fantastic and last about a month.  I have them on a subscription so once he''s done with one, a new one is waiting.   Highly recommend!', 'Jamie L.', '', true, true, 0, TIMESTAMP '2025-08-19T15:56:39.459379Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'LIFESAVER FOR CHEWING PUPS!', 'Okay so our doodle puppies were chewing on every tree stick in the yard!  We decided to purchase the Mumbies and we did in several different sizes for our puppies (5 months old now) and our daughters 3 yr old Labradoodle.  They all LOVE there Mumbies!!! It''s alot better than chewing on yard debris which would make them vomit sometimes.  So now they feel like they have a stick to chew on BUT it''s a safe stick and guess what NO VOMITTING!!!  It''s nice quiet time for them with very devoted chewing on the Mumbies!  Thank You as it was a lifesaver!', 'Holly W.', '', true, true, 0, TIMESTAMP '2025-08-19T01:34:00.445813Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'FINN LOVES HIS MUMBIES!', 'My boy, Finn, loves his Mumbies! He chews and chews all day. If he eats any, it comes out just fine on the other end. I may need to order more than one at a time. He destroys them.', 'Trip Werrell', '', true, true, 0, TIMESTAMP '2025-08-18T15:23:03.423184Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'SAVING MY DECK! 🐾', 'Perfect for your dog/s that love to chew on wood!! I wish I would’ve known about these sooner before our dogs destroyed our deck 🤦🏼‍♀️ lol ', 'Robin S.', '', true, true, 0, TIMESTAMP '2025-08-16T10:46:08.850254Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'HOLDS UP TO PUPPY CHEWING!', 'Quality product. Holds up for serious heavy chewers. 2 Doberman puppies have their work cut out for them.  Hopefully stops them from eating sticks.', 'Arthur', '', true, true, 0, TIMESTAMP '2025-08-12T19:43:26.125856Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great chews for a super-chewer!', 'Our super-chewer loves her Mumbies sticks!', 'JDM', '', true, true, 0, TIMESTAMP '2025-08-12T12:21:33.025128Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'BOONE APPROVED!', 'Boone my 8 month old lab love this chew. We got the XL size and it is the perfect fit for him. Keeps him busy 😊', 'Jennifer T.', '', true, true, 0, TIMESTAMP '2025-08-12T02:26:52.410250Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/bff4b8de-c3cb-4d12-98fd-6ab4465c0ea7.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/c370ae4d-5ea6-4c3b-99d3-e3b3dd4f8cac.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'German Shepherd Approved!', 'Ace loves his!  Much better quality than competitors and more natural than other chews made from artificial things that end up sharp and hurting his gums.', 'Travis C.', '', true, true, 0, TIMESTAMP '2025-08-12T01:58:10.821450Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Gotta try at least once!!!', 'Bought once not expecting my pup to fall in love! Having a golden retriever there is never enough happy chewing.  It soothes her and keeps her and us happy!!', 'Suzanne H.', '', true, true, 0, TIMESTAMP '2025-08-08T19:42:00.967679Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Winnie and Oliver are Mumbies #1 fans!', 'I saw these chews in an ad and loved the idea of an all natural, organic, softer chewing bone. At first my dogs were like “what is this flavorless bone that I can’t eat?”, but taking the chews away after 15 minutes each night made them really intrigued with it. Now, they can’t WAIT to chew them each night! Really great product and will be buying another set soon!', 'Andrew', '', true, true, 0, TIMESTAMP '2025-08-07T01:52:29.713022Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/c90ef6ae-0f22-472d-aedd-777e4590d1ed.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/7e5e96ad-9cf8-4d34-91f2-e59951b5afd6.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'SUPER CHEWER APPROVED!', 'My dog is a super chewer and loves these. It usually takes about a week or two before he gets them shredded down to a size where they have to be thrown away. I love that they don’t splinter so I don’t worry about him getting a sliver in his mouth that can get infected. Also it doesn’t come apart into pieces that he can choke on. ', 'Jason M.', '', true, true, 0, TIMESTAMP '2025-08-06T15:50:31.434194Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 4.0, '', 'Very large & or dog keeps busy with it', 'Paula', '', true, true, 0, TIMESTAMP '2025-08-05T11:39:24Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Chewrrific!', 'Our Tapi loved his first Mumbies chew stick. Will be buying more. ', 'Carol K.', '', true, true, 0, TIMESTAMP '2025-08-05T00:45:01.460438Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'Quick delivery. As advertised. Strangely, my dog won’t touch it!', 'Fred', '', true, true, 0, TIMESTAMP '2025-08-02T17:56:11Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Love this chew!', 'This chew is awesome, Great for a heavy chewer and keeps them busy. Long lasting.', 'Joleen L.', '', true, true, 0, TIMESTAMP '2025-07-28T22:14:40.671000Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great for dogs who need to chew', 'These have become a favorite for my super chewer. The advice to size up if you have an aggressive chewer is spot on.', 'Maureen D.', '', true, true, 0, TIMESTAMP '2025-07-26T16:47:55.344618Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 4.0, 'GREAT FIND! MUMBIE LOVE!', 'Our little dog loves the challenge and satisfaction of her Mumbie! While she can get small bits off it takes hard work and I love that it''s nontoxic. We recommend getting a size larger than you might think or opt for two sizes! This will be a favorite for years!', 'Pauline D.', '', true, true, 0, TIMESTAMP '2025-07-25T11:14:08.962999Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'Our pups LOVE Mumbies! I am so glad to have found a safe alternative to planstic chews!', 'Evelyn', '', true, true, 0, TIMESTAMP '2025-07-24T17:52:48Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'DOGS LOVE ''EM! NO PLASTIC!', 'My dogs love these chews!! I like that they are not plastic! ', 'Kristen C.', '', true, true, 0, TIMESTAMP '2025-07-20T12:50:11.066103Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Awesome! Puppy approved! ', 'My puppy loved it!  I love that it’s safer for him, he spends a long time chewing on it, he’s very happy. ', 'Louis B.', '', true, true, 0, TIMESTAMP '2025-07-20T01:37:26.867013Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Happy pup!', 'My dog loves her Mumbies chew!  I love that it doesn’t splinter or have sharp edges.', 'Nina M.', '', true, true, 0, TIMESTAMP '2025-07-16T21:43:56.592600Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Wonderful chews for your super chewers ', 'My 2 "super chewers" LOVED the mumbles original chews. They spent a few hours each day munching on the wood chews', 'Joanne S.', '', true, true, 0, TIMESTAMP '2025-07-10T00:44:26.742687Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Wood chews ', 'Really great .!!', 'Michele M.', '', true, true, 0, TIMESTAMP '2025-07-01T14:39:55.211177Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'DOGGO APPROVED! 🐾', 'This is the second order and my dog is in love with these!  So happy with whole experience from ordering to fast shipping to quality.  My golden retriever loves chewing so she thoroughly enjoys every bite!', 'Suzanne H.', '', true, true, 0, TIMESTAMP '2025-06-19T16:30:02.703576Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 4.0, 'Golden girls approve', 'I have 2 golden retrievers that absolutely love to chew on sticks. I tried replacing their sticks with these. It sort of worked. They like these, but they''re expensive so I can''t bring myself to let them be "outside" toys. The Girls really prefer to get their chew on outside.', 'Nancy V.', '', true, true, 0, TIMESTAMP '2025-06-17T19:16:41.979250Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'LOVE IT! GREAT CHEW!', 'Great chew!  I have a 9 month old Labrador and 3 y/o Golden. Field dogs. They LOVE their chew!!  I will be getting more soon!!

Warning!  If chewed in the house you will be vacuuming wood bits!  Good sign!  These guys have strong jaws and no splinters, just small “crumbs” not chunks of wood!!', 'Jennifer E.', '', true, true, 0, TIMESTAMP '2025-06-11T00:38:12.507247Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/6ee49809-392b-4128-a5c6-84897e01fec7.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/5a559385-106b-4026-95d4-3fbeb8ea738c.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'GREAT WOOD QUALITY!', 'Love the quality of the wood. For me it’s important that my dog is not “eating” plastic. Last a long time also.', 'Sigrid O.', '', true, true, 0, TIMESTAMP '2025-06-06T20:53:36.080569Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'THE BEST CHEW!', 'The original chew is the best! My dog loves it and has yet to be able to destroy it.', 'Marcy B.', '', true, true, 0, TIMESTAMP '2025-06-04T21:48:19.070477Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Dog loves', 'Great toy!', 'Will O.', '', true, true, 0, TIMESTAMP '2025-06-02T15:54:32.782979Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'DOGGO APPROVED CHEW!', 'My dog loves her chew. Great alternative to her eating sticks that splinter it can make her sick.', 'Maria V.', '', true, true, 0, TIMESTAMP '2025-05-31T22:55:58.385657Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/38ed61d6-0eb8-4792-afd4-04bc5639596a.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'STILL STANDING AFTER 2 WEEKS!', 'My 90lb golden is an aggressive chewer and typically destroys toys within hours. He loves his Mumbies and they are still going strong 2 weeks later!', 'Shelby', '', true, true, 0, TIMESTAMP '2025-05-30T13:28:01.764241Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Dogs love them', 'My dogs love them that''s all they want to chew on.', 'Tina W.', '', true, true, 0, TIMESTAMP '2025-05-30T00:58:45.998085Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Mumble Joy', 'Just got Butter’s mumbies.   She is an 9 month old poodle/lab and such an aggressive chewer.  Although she does not like most products.  She took to her mumbies immediately. I am as happy as Butter is.  Already told my sisters together them.
Never run out please 💓', 'Nonni', '', true, true, 0, TIMESTAMP '2025-05-28T21:35:04.963918Z', '[]'::jsonb);
