INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Poodle Approved', 'I’m so happy I found Mumbies. Our dog loves it and we will order again!', 'Keith B', '', true, true, 0, TIMESTAMP '2025-05-19T00:01:55.492435Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great service, great product', 'I have a 55 pound chewer. She loves to chew everything. I first got her the large chill and it kind of broken into splinters and was not to my satisfaction. I emailed customer service and they were just lovely to deal with. They suggested I try the extra large and just pay for the shipping. Which I did. I returned two of the three that my dog had not used and I have to say the extra large was perfect. So I like the product. And I like the company.', 'Peggy B.', '', true, true, 0, TIMESTAMP '2025-05-16T21:29:46.372325Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'MY PUPS LOVE MUMBIES!', 'My pups LOVE mumbies!! Their customer service has been great too! Placed a few orders already and they all came in a timely manner! Looking forward to ordering again!', 'Dani V.', '', true, true, 0, TIMESTAMP '2025-05-16T19:27:34.387604Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/afee972f-995c-44db-8005-f835e6f69188.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'I do think the medium is perfect for now as it is much more carriable for Storm. I’ll be getting a few so i can continue to cut back on getting her as much plastic/etc toys and focus on more natural ones.', 'The', '', true, true, 0, TIMESTAMP '2025-05-16T13:43:09Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'Storm absolutely LOVES these things! 
Time will tell which size is right for her for now, but she likes them both SO much!!!', 'The', '', true, true, 0, TIMESTAMP '2025-05-15T22:12:01Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'She Loved them', 'Daniel', '', true, true, 0, TIMESTAMP '2025-05-06T03:21:48Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great for super chewers', 'Excellent quality for the price. My dog who is a super chewer and can destroy anything has not even made a dent in his xl mumbie.  Highly recommend. Does not make a mess or leave stains', 'Kim T.', '', true, true, 0, TIMESTAMP '2025-04-25T21:16:53.796393Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'My dogs loves the large one ! I bought a large for my mountain cur mix and a medium for my golden retriever puppy and they both will chew on the large ! Keeps them busy and they love the wood !', 'Sheri', '', true, true, 0, TIMESTAMP '2025-04-21T19:17:19Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Safe & Long-lasting', 'These are the absolute best long-lasting dog chews! Yes, they are a bit messy as the wood disintegrates into tiny pieces and gets left behind on your flooring, but they are SAFE! No sharp or large pieces being ingested! My Rottsky is a trash hound who will eat almost anything & has had pricey abdominal surgery because of it. With these Mumbies, he gnaws & nibbles them down over a few months and no more pricey vet bills.', 'Melissa D.', '', true, true, 0, TIMESTAMP '2025-04-20T23:07:22.308123Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/85dea99e-f8f1-4923-ad49-08651421239a.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Finally something my dogs can''t destroy in 24 hrs', 'My 7 dogs love these new chews. They are aggressive chewers when it comes to treats and these are holding up', 'Carol Z.', '', true, true, 0, TIMESTAMP '2025-04-20T01:00:36.963883Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great for Bernese Pup', 'Our 5 month old Bernese puppy LOVES this chew. We bought it because she loves destroying sticks outside and wanted to give her that same chewing joy inside with us but without all the mess!', 'KATHERINE S.', '', true, true, 0, TIMESTAMP '2025-04-19T23:09:05.921339Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great product', 'I have lots of logs in my yard but the dogs can have these in the house. They don’t splinter. Great product.', 'JoAnn R.', '', true, true, 0, TIMESTAMP '2025-04-19T18:05:31.328637Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/5de08d65-3bfd-4c4e-96ad-071dc2e1a50f.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/e8d9efb5-16a6-4303-a671-c7af7eaf87a0.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'MUMBIE CHEW STICK LIFE!', 'WE LOVE MUMBIE CHEW STICKS!!! My girl is a heavy chewer and a huge fan of these sticks. I feel comfortable giving them to her. Love the goal of the company and happy to help support their cause.', 'Tina H.', '', true, true, 0, TIMESTAMP '2025-04-17T22:24:47.015832Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', '', 'Dusti Johns', '', true, true, 0, TIMESTAMP '2025-04-17T21:57:01.259771Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'MUMBIES FOR THE WIN!', 'Mumbies has surpassed my expectations with the quality of their chews and their treats! 
I also want to mention their customer service and communication with ordering is top notch!
My fur baby Sophia loves her chews so much and as an aggressive chewer, the Mumbies has held up and keeps her busy for hours! Can’t be more happier!', 'Hannah P.', '', false, true, 0, TIMESTAMP '2025-04-12T19:54:31.752721Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/d6384851-5a70-4fde-8cf3-6d86428fd542.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/e6b3a6c3-ae55-435b-947f-d1c9f2c0a3a5.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/4a0b750f-894a-4ca1-9832-7c705e7d9c37.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'The coconut rope was a hit!!
Still waiting for baby girl to try the original chew. She''s still teething. 

Great product💚', 'Lavinia', '', true, true, 0, TIMESTAMP '2025-04-11T18:22:26Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Excellent', 'My dog loved this chew.', 'Lisa H.', '', true, true, 0, TIMESTAMP '2025-04-05T21:01:28.613306Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'PRIZED POSSESSION!', 'Love supervised chewing outside!! My german shepherd just destroys toys and is not that interested in the solid rubber toys out there. His chew is a prized posession', 'Hannah B.', '', true, true, 0, TIMESTAMP '2025-04-03T13:14:14.485451Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'Golden retriever LOVES it! Finally a long lasting chew.', 'Samantha', '', true, true, 0, TIMESTAMP '2025-04-01T20:39:50Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Gage bone', 'This is the best bone we have found. Our puppy has chewed up every toy we have given him. This lasted far longer and keeps him occupied.', 'Aline T.', '', true, true, 0, TIMESTAMP '2025-03-22T15:09:54.791635Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Awesome product', 'cool product', 'erald', '', false, true, 0, TIMESTAMP '2025-03-08T16:05:27.841127Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Awesome product!!', 'I''ve got two heavy chewers, and they absolutely love these Mumbies. They chew on them every day. I like the fact that the stick flakes off and doesn''t splinter. This was our first purchase, but we''re definitely going to be buying here again.', 'Alan E.', '', true, true, 0, TIMESTAMP '2025-03-03T03:28:08.635031Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/6cd2a4f7-7193-4959-a006-693468939c3b.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great bone', 'I definitely recommend!', 'Tracy F.', '', true, true, 0, TIMESTAMP '2025-03-02T08:33:13.475059Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'LIFE SAVER CHEW! 🐾', 'One of my 3 dogs had always been addicted to chewing everything wood inside and out! She is a very active chewer! This Chew has been an absolute life saver! The best thing I could have ever gotten her! She is a 55 pound bull terrier/boxer mix and this size was perfect! At first it looked way too big but actually worked out! She has chewed it into a pencil and spends a lot of time with it! It’s safe, durable and slightly messy🤣 Other than that I am grateful to have found this chew and I am most definitely a forever customer! I believe I ordered the XLarge for those interested!! Thank you Mumbies!!', 'Garilyn D.', '', true, true, 0, TIMESTAMP '2025-02-25T19:10:03.223482Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '5 Stars from a Chewer', 'My dog loves it! And she''s a big chewer!', 'Markie F.', '', true, true, 0, TIMESTAMP '2025-02-24T23:48:49.999791Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/ec630b5c-1f21-4ec4-8885-c9f92ad2fbca.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Mumbies and puppies go together like a baby and a bottle!', 'Mumbies are my dog''s go-to chew. He has other choices, but he always searches for his Mumbies! Mumbies are a great bedtime sedative for my puppy. He chews on them to fall asleep, and I smile when I roll over on a favorite chew that finally put him to sleep!', 'Jeannie', '', true, true, 0, TIMESTAMP '2025-02-24T20:45:35.819302Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great chews', 'I will be ordering more, my golden retriever, loved these.', 'Michelle C.', '', true, true, 0, TIMESTAMP '2025-02-24T16:02:45.299616Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Dogs love them but very messy!', 'My three dogs, 2 Clumbers and 200+lb mastiff, all really love these Mumbies.  We chose to get the XL size because the biggest size was out of stock. The XL was plenty big enough for my 3 girls. They are obsessed with them.  My only complaint is that they are soooooo incredibly messy.  I have to vacuum at least twice a day to get all the wood pieces.  I finally had to take them away and I will be saving them for outside only once it gets a little warmer. I love them, I just wish they weren’t sooo messy.', 'Kerri B.', '', true, true, 0, TIMESTAMP '2025-02-22T21:19:15.532717Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/62bdad95-3069-4ef9-a091-fbaeb4b724c8.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/6e919078-9089-42f0-bc18-4270cd3bf995.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/a17c3c43-945b-4fcf-9ddd-eb185c6131a4.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/691c8f73-8b06-4940-b693-31325f958729.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Grady approved!', 'My pup''s a big-time chewer! We cudn''t find anything he didn''t tear up or destroy, until my daughter-in-law got him a Mumbie real wood chew. He''s one happy pup when he has his Mumbie! And they keep him off the legs of my furniture!
Really good product! 👍🏻', 'Monica O.', '', true, true, 0, TIMESTAMP '2025-02-20T03:48:49.657653Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/b2a1504e-b62b-40c4-a707-68295f6e3c8e.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/c73c8e8d-08b1-4fce-a59b-f956e3afe177.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'HE CAN''T GET ENOUGH!', 'I love that the Mumbies chew is made of natural wood.  I got the XL for my 70lb dog who loves to chew on falling tree branches outside.  At first he was hesitant because this was so much larger than what he''s used to, but he warmed up quickly and now he can''t get enough of it!  I highly recommend this great product!', 'Jamie L.', '', true, true, 0, TIMESTAMP '2025-02-19T01:22:10.792861Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'We Love Mumbies!', 'My two Australian Koolies love Mumbie Bones!!  These are so much safer than traditional bones and even my twelve year d liver shunt dog can have these!', 'Karen K.', '', true, true, 0, TIMESTAMP '2025-02-18T06:41:49.906145Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'HAPPY BOY WITH MUMBIES!', 'My dog Max loves his Mumbies and getting to have an "indoor" stick! He would get sad as I wouldn''t let him bring branches in the house. With Mumbies he''s a happy boy!', 'Patricia P.', '', true, true, 0, TIMESTAMP '2025-02-18T00:50:00.994971Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'TAILS WAGGING! 🐾', 'Mumbies get tails wagging! They are a big hit with a Newfie, a Berner and two Huskies 👅. Hours of fun and no bleeding gums or plastic bits left on the floor to step on when making treks from the bedroom to the kitchen.', 'Teresa W.', '', true, true, 0, TIMESTAMP '2025-02-17T00:53:58.001866Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'SIMBA''S NEW FAVORITE!', 'My dog loves his Mumbies chew!! He loves to carry and chew on sticks outside, but is always sad when he can''t bring them inside. Mumbies has created a great way for Simba to bring his favorite activity indoors. And most importantly it''s safe! I frequently worry about him ingesting pieces of wood when chewing outside, but I don''t have those concerns with Mumbies.', 'Andrea', '', true, true, 0, TIMESTAMP '2025-02-15T23:21:42.327258Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/2488013b-1c9d-49b6-852c-ff89da0552a6.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/cdbaea6c-f395-4afb-8646-d5002a1ad4cc.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'BROOKLYN''S FAVORITE!', 'Brooklyn loves these. They keep him busy for hours.', 'Heather B.', '', true, true, 0, TIMESTAMP '2025-02-14T22:16:13.989563Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/ba5ec456-ee8d-467c-a95e-5ac4b15588b6.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/a9b5cd98-b35e-428a-9b9b-581722267598.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great Chew!', 'So happy to find a chew that will outlast my serious chewer!', 'Keri P.', '', true, true, 0, TIMESTAMP '2025-02-07T12:11:08.410976Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'My dog loves these!', 'Mary', '', true, true, 0, TIMESTAMP '2025-01-23T18:46:17Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'PUPPY APPROVED!', 'I bought these for my puppy and though it was on back order (due to very high demand) they came right on time for her adult teeth! While waiting, I bought another brand off chewy thinking it would do. It barely got used and now that the Mumbies chews came in she ignores the other one completely. She finished one stick in around 2 months, where everything else lasts an hour or she gets bored. It sheds some tiny pieces sometimes but since it’s not a sticky bone it’s very easy to vacuum up. I got different sized chews and the root, and will definitely be ordering again!', 'Emily Sullivan', '', true, true, 0, TIMESTAMP '2025-01-02T14:32:15.773449Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/fba977d9-22e3-44e1-af08-25149dd3eb8f.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/c0600e3c-1610-4ac2-af45-1e27514feaba.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Dogs love them 🥰', 'Both our dogs love these!!! So excited to find a safe replacement to nylon bones that also doesn’t shred and leave pieces all over the house. Super happy customer!', 'Rachel', '', true, true, 0, TIMESTAMP '2024-12-30T14:22:05.522684Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/4c836d7d-3f56-41d3-bf55-e213d9d57195.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Saved my furniture!!!', 'My dog used to chew my kitchen chairs and table out of frustration when we left her home!! Now she chews the large chew instead!!! Thank you!!!', 'Tracy I.', '', true, true, 0, TIMESTAMP '2024-12-29T15:58:44.876216Z', '["https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/d552645d-930a-4b51-804f-4ecc4a29f83d.jpeg","https://klaviyo.s3.amazonaws.com/reviews/images/WHRmip/86a70b34-ec7a-4712-91ba-9681cc334972.jpeg"]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 3.0, '', 'my dog loves it but it’s SOOOOOOO messy leaving pieces everywhere', 'Tara', '', true, true, 0, TIMESTAMP '2024-12-29T15:04:25Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Excellent product...strong chewer approved', 'My dog is a strong chewer and this works well.  She can''t destroy it like other chews.  It will last a very long time.', 'Marcia L.', '', true, true, 0, TIMESTAMP '2024-12-28T23:00:49.682562Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Best toy ever', 'Best thing since sliced bread! My dogs will fight over these everytime
Definitely the chosen toy', 'Susan m.', '', true, true, 0, TIMESTAMP '2024-12-28T20:26:01.334923Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'A good chew from someone new', 'My dog loves chewing sticks, but the vet says it''s dangerous.  Got the Mombies chews as an alternative - and she loves them!

A startup with more success than they antcipated, stock was low and delivery was a bit slow - but worth the wait!', 'JD', '', true, true, 0, TIMESTAMP '2024-12-28T12:13:12.147480Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', 'My dogs love these! They’re good for their teeth and safer than plastic. Will buy again!', 'Rebecca', '', true, true, 0, TIMESTAMP '2024-12-27T01:38:37Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'MEDIUM DIDN''T LAST, LARGE IMPRESSED!', 'I’m bought 2 large and one medium, not sure how they would go over with my 3 labs.  The medium was broken down within 30 minutes.  The large ones however held up really well, and these three are destructive.', 'Violet', '', false, true, 0, TIMESTAMP '2024-12-25T02:30:43.113021Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Nothing nasty in these chewies!', 'My dog Babaloo loves Mumbies, and I am happy that he does because he is not digesting micro-plastics, "natural" flavoring, or anything nasty. And no animals had to die for my dog''s treat.', 'Jeannie H.', '', true, true, 0, TIMESTAMP '2024-10-16T00:43:02.806759Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, '', '', 'Bernadette Phelan', '', true, true, 0, TIMESTAMP '2024-09-30T14:05:38.796116Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great for big chewers', 'My EXTREMELY aggressive chewer loves these so much!', 'Kelly W.', '', true, true, 0, TIMESTAMP '2024-09-28T16:16:45.020807Z', '[]'::jsonb);
INSERT INTO product_reviews (product_id, rating, title, content, reviewer_name, reviewer_location, verified_purchase, is_approved, helpful_count, created_at, image_urls) VALUES ((SELECT id FROM products WHERE name = 'Mumbies Original Wood Chew'), 5.0, 'Great chew!', '', 'Rebecca Q.', '', true, true, 0, TIMESTAMP '2024-09-26T18:09:31.872299Z', '[]'::jsonb);
